apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 600; done;']
      volumeMounts:
        - name: cm-volume
          mountPath: /etc/config
      resources:
        {}
  restartPolicy: Never
  volumes:
    - name: cm-volume
      configMap:
        name: sample-cm        
