apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  containers:
  - image: busybox
    name: pv-pod
    resources: {}
    command: ['sh', '-c', 'echo yolo > /etc/pv/stuff.txt']
    volumeMounts:
    - name: local-pv
      mountPath: /etc/pv
  restartPolicy: Never
  volumes:
  - name: local-pv
    persistentVolumeClaim:
      claimName: sample-pvc
      
