apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  restartPolicy: Never
  containers:
  - image: busybox
    name: secret-env-pod
    command: ['sh', '-c', 'env | sort']
    resources: {}
    envFrom:
      - secretRef:
          name: literal
          
