apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - image: busybox
    name: secret-volume-pod
    command: ['sh', '-c', 'cat /etc/secret/password']
    resources: {}
    volumeMounts:
      - name: from-secret
        mountPath: etc/secret
  restartPolicy: Never
  volumes:
    - name: from-secret
      secret:
        secretName: literal