apiVersion: v1
kind: Pod
metadata:
  name: volume-pod-host
spec:
  containers:
  - image: busybox
    name: volume-pod-host
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
    - name: host-vol
      mountPath: /test
  volumes:
  - name: host-vol
    hostPath:
      path: /tmp
