apiVersion: v1
kind: Pod
metadata:
  name: volume-pod-emptyDir
spec:
  containers:
  - image: busybox
    name: volume-pod-emptyDir
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}
