# targets pods with label 'app: nginx-deployment' and that have port 80 open (targetPort)
# service can be reached with SVC.NS:PORT, e.g. nginx.default:8080 or nginx:8080
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: nginx
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deployment
  type: ClusterIP
