apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeselector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeselector
  template:
    metadata:
      labels:
        app: nodeselector
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      nodeSelector:
        workloadLabel: app
