apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodename
  name: nodename
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodename
  template:
    metadata:
      labels:
        app: nodename
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      nodeName: 3-node-cluster-m03
